version: '3'
services:
  postgres:
    image: postgres
    container_name: Demo_WebGL
    ports:
      - 6500:5432
    env_file:
      - ./web.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
